### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by LinuxpowerLudo** [miroblog/limit_orderbook_prediction#1]
Hello Lee,

Can you fix the code ? there are many problems on the keras network !

**Comment by miroblog** [comment]
could you print the logs? 

the code is straight forward. 
extract features from limit orderbook
build training data
train
validate

**Comment by LinuxpowerLudo** [comment]
Hello Lee,

I try the cnn_lstm.py :

First error : AttributeError: 'CNNLSTM' object has no attribute 'nb_filter'

I have fix it with (#print(self.nb_filter))

But after i have a second error :

ValueError: Input 0 is incompatible with layer conv2d_1: expected ndim=4, found ndim=3

If you can fix the code. I would like compare rnn vs cnn_lstm performance.

Many thanks.

Regards
Ludo.

**Comment by miroblog** [comment]
O.K. fixed some issues. clone the repo and try out again...

although the sample data is provided.  
you should try the model with larger dataset.  

for cnn-lstm
apply conv : (batch_size, 50, 48, 1) -> (batch_size, 46, 1, 50)  
input to rnn : (batch_size, 46, 1, 50) ->  (batch_size, 46, 50)    

try experimenting with different `self.kernel_size_x`

**Comment by LinuxpowerLudo** [comment]
Ok many thanks Lee !

The code work perfectly ! but the performance is poor compared the rnn.
